<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>loterie</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
</head>
<body>
    <h1>Tirage de la loterie</h1>
    <p>les numéros du soir sont les suivants: </p><br>
    <p><?php echo $tirage[0]; ?></p><br>
    <p><?=   $tirage[1]; ?></p><br>
    <p><?php echo $tirage[2]; ?></p><br>
    <p><?php echo $tirage[3]; ?></p><br>
    <p><?php echo $tirage[4]; ?></p><br>
    <p><?= $tirage[5]; ?></p><br>

</body>
</html>